# Configuration file for your Jekyll site
title: Programming Notebook
description: Organize, Collaborate, and Innovate
theme: minima

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false